//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEOOG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exchange
    {
        public int ExchangeID { get; set; }
        public string ExchangeName { get; set; }
        public string ExchangeGetGive { get; set; }
        public string ExchangeQTY { get; set; }
        public System.DateTime ExchangePostTime { get; set; }
        public string ExchangeUserName { get; set; }
    }
}
