//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEOOG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantIndex
    {
        public int PlantID { get; set; }
        public string PlantName { get; set; }
        public string Information { get; set; }
        public string LinksMore { get; set; }
        public string PhotoSrc { get; set; }
    }
}
